### ISSUE TITLE
Runing on stereo fisheye 

### ISSUE THREAD

**Issue by smileyenot983** [sair-lab/AirVO#102]
Hi. Did anyone run AirVO with in stereo fisheye setup?

**Comment by xukuanHIT** [comment]
@smileyenot983 Hi, I have tried the stereo camera. As features are detected on the images undistorted by the OpenCV, so the VO performance relies on the undistortion. For fisheye cameras with minor distortion, such as the UMA-VI dataset, the undistortion is fair, but for fisheye cameras with severe distortion, we find the OpenCV's undistortion is not very good.
