### ISSUE TITLE
Regarding computer configuration requirements

### ISSUE THREAD

**Issue by Lmy971109** [sair-lab/AirVO#104]
Dear author:
  Thank you so much for the great work you do for VO! Excuse me, does the configuration of this computer meet the environment configuration of AirVO? It is using dual system Ubuntu18.04. The ROS version is melodic and CUDA is 11.3.
<img width="518" alt="0101" src="https://github.com/sair-lab/AirVO/assets/108608935/d6a8d98d-9d6f-460f-bcd4-b66f9fb59ea3">

**Comment by xukuanHIT** [comment]
@Lmy971109 Hi, the GPU is ok, but we have not tried AirVO with CUDA 11.3. And what is the driver version on your computer?

**Comment by Lmy971109** [comment]
Dear author:
   The drivers installed on this computer are as follows:
<img width="520" alt="图片" src="https://github.com/sair-lab/AirVO/assets/108608935/358e77d1-f15b-45a6-a40b-5d25c5db4c6b">

**Comment by xukuanHIT** [comment]
The driver is ok. You can try the docker first

**Comment by Lmy971109** [comment]
OK,Thanks very much



---- Replied Message ----
| From | Xu ***@***.***> |
| Date | 04/22/2024 18:44 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [sair-lab/AirVO] Regarding computer configuration requirements (Issue #104) |

The driver is ok. You can try the docker first
