### ISSUE TITLE
Relocation in map?

### ISSUE THREAD

**Issue by antithing** [sair-lab/AirVO#107]
Hi! Is it possible to store the point and line map, and relocalize in the existing map on a second run?

Thanks!

**Comment by xukuanHIT** [comment]
@antithing Sure. But the map is not good enough now as loop closures are not detected in this version. An improved version with loop detection and relocalization modules will be released soon.

**Comment by antithing** [comment]
Great! Do you have a timeline on release? Thank you again!

**Comment by xukuanHIT** [comment]
We aim to release it within two months.
