### ISSUE TITLE
Ubuntu 20.04 docker enviroment error: unknown or invalid runtime name: nvidia.

### ISSUE THREAD

**Issue by Lx017** [sair-lab/AirVO#113]
Hi, I have already pulled the docker successfully (with sudo if that matters) and run:
sudo docker run -it --env DISPLAY=$DISPLAY --volume /tmp/.X11-unix:/tmp/.X11-unix --privileged --runtime nvidia --gpus all --volume ${PWD}:/workspace --workdir /workspace --name air_slam xukuanhit/air_slam:v1 /bin/bash
However, docker gives me:
docker: Error response from daemon: unknown or invalid runtime name: nvidia.
what is the solution?

**Comment by xukuanHIT** [comment]
@Lx017 Hi, you need to install the [nvidia docker](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html).

**Comment by Lx017** [comment]
I cannot get configuration and setup right in any way on Ubuntu 20.04, main issue is from nvidia and docker. But 22.04 can work.
