### ISSUE TITLE
Could the AirVO run bag dateset 

### ISSUE THREAD

**Issue by ZouZhijians** [sair-lab/AirVO#60]
Hello ,In order to test the AirVO ,I download other datasets but they are bag files. Could the AirVO run bag dateset ? If could,How?

**Comment by ZouZhijians** [comment]
I know I need to change bag files into ASL datasets ,Is there any tools which can help me?

**Comment by xukuanHIT** [comment]
@ZouZhijians Hi, this is the [script](https://entuedu-my.sharepoint.com/:u:/g/personal/kuan_xu_staff_main_ntu_edu_sg/EVqjOjV6RNFMsmM_6Vc6NoABhhFBMYTpd51PXL-jVGerqA?e=fJYo2C) I used.

**Comment by ZouZhijians** [comment]
Appreciate！I will try.
