### ISSUE TITLE
Windows, without ROS?

### ISSUE THREAD

**Issue by antithing** [sair-lab/AirVO#66]
Hi! Thank you for this code. Would it be possible to run it on Windows, without ROS?

**Comment by xukuanHIT** [comment]
@antithing Hi, thanks for your interest. AirVO is unable to run on Windows without ROS now.

**Comment by antithing** [comment]
Hi @xukuanHIT thanks! I have modified the code to compile on Windows, and I have it running on the euroc dataset.

However, i see this message:

`Failed when extracting point features !
`
about every five frames. 

It looks like this happens when inference fails in Superpoint, but why would this be happening?

Do you have any ideas here?

Thank you!

**Comment by antithing** [comment]
Ah, this was an error with my dataset loading modifications, I have it running well now! .
