### ISSUE TITLE
UMA-VI Dataset

### ISSUE THREAD

**Issue by HJMGARMIN** [sair-lab/AirVO#70]
Hello, I want to use your great work in my paper. However, I cannot download the UMA-VI dataset from https://mapir.isa.uma.es/mapirwebsite/?p=2108&page=2. I also try the link provided by the authors as below:
![image](https://github.com/sair-lab/AirVO/assets/52454672/3aef759a-df09-4eeb-98e3-e948309f471c)

But I cannot sign in the website. Can you provide an onedrive or google cloud link of the dataset? Thanks!

**Comment by xukuanHIT** [comment]
@HJMGARMIN Hi, I only have a partial sequence. You can use this [link ](https://entuedu-my.sharepoint.com/:f:/g/personal/kuan_xu_staff_main_ntu_edu_sg/Emr16YVWbjVNhjaMt8qRGHABr2R_D_-WcHUvJDDePtNsGA?e=FOO2R5)to download the four sequences used in the paper.

**Comment by HJMGARMIN** [comment]
Thanks for your reply. How did you download the four sequences? Do you have the link that you used?

**Comment by xukuanHIT** [comment]
I previously requested the download link for the indoor illumination variation dataset from its author.

**Comment by zhongxiangrong** [comment]
I have contacted the corresponding author of OIVIO. He stated that it may be due to changes in the server supplier. He will solve this problem as soon as possible.

> @xukuanHIT Do you have any link of OIVIO dataset? The original links are not available for public now (https://arpg.github.io/oivio/trajectories/)

**Comment by xukuanHIT** [comment]
@quachconghoang Hi, I have uploaded some sequences to OneDrive. You can download using this [link](https://entuedu-my.sharepoint.com/:f:/g/personal/kuan_xu_staff_main_ntu_edu_sg/EtabKNOPBPBMmjJXbN4A8wMB0MTZmeZlnfAi7bskgfAr7A?e=Jn0S3B).

**Comment by quachconghoang** [comment]
Many thanks @xukuanHIT, @zhongxiangrong
