### ISSUE TITLE
Lightglue. 

### ISSUE THREAD

**Issue by antithing** [sair-lab/AirVO#80]
Hi,  I am looking to speed up the runtime of this project, and am thinking that swapping superglue for lightglue might help.

Do you have any plan to implement this? Or pointers that might help me?

Thanks!

**Comment by xukuanHIT** [comment]
Yeah, we will replace superglue with lightglue in our following VIO version if it can achieve the similar performance.

**Comment by antithing** [comment]
Amazing. Do you have an estimate timeline for the next updates? Thanks!

**Comment by xukuanHIT** [comment]
It will be released by the end of the year if everything goes smoothly.
