### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Cai-RS** [sair-lab/AirVO#87]
Thank you for your great work! 
I'm not very familiar with using TensorRT. I have a question, in function "bool SuperPoint::build()", what is the code after the if(deserialize_engine()){}" part for? 
![1](https://github.com/sair-lab/AirVO/assets/92929904/985d4d89-a135-4633-b9f0-73c07fa53102)

for leveraging TensorRT's API to build a network after deserialization fails?

**Comment by yuefanhao** [comment]
@Cai-RS I think so, these two engines always coexist in the GPU in actual work, after all, reloading will take time. As for splitting GPU memory into two parts, I'm sorry I haven't looked it over in depth.
