### ISSUE TITLE
camera_config

### ISSUE THREAD

**Issue by t676290894** [sair-lab/AirVO#90]
"Thank you for your work. As a beginner, I have learned a lot from it. I am not very familiar with some parameters in your camera intrinsic file. I understand that LEFT.D and LEFT.K are obtained from the dataset. Could you please explain how LEFT.R and LEFT.P are obtained?"
![image](https://github.com/sair-lab/AirVO/assets/147059017/6a5929c4-f302-4a47-aeba-d60266735a79)

**Comment by xukuanHIT** [comment]
@t676290894 Hi, they are outputs of [stereoRectify](https://docs.opencv.org/4.2.0/d9/d0c/group__calib3d.html#ga617b1685d4059c6040827800e72ad2b6).

**Comment by t676290894** [comment]
Thanks sincerely for your help

**Comment by xukuanHIT** [comment]
@t676290894 It's the output of [evo_ape](https://github.com/MichaelGrupp/evo/wiki/Metrics)

**Comment by t676290894** [comment]
Thank you sincerely for your answer! I will close this issue.
