### ISSUE TITLE
SuperGlue推理结果为NaN

### ISSUE THREAD

**Issue by Dongdong-NEU** [sair-lab/AirVO#95]
哈喽 感谢您的开源工作~
        我在使用公共数据集Euroc运行AirVO的时候一直无法初始化地图, 排查原因最后发现是在superglue在推理的时候 `auto *output_score = static_cast<float *>(buffers.getHostBuffer(superglue_config_.output_tensor_names[0]));` 中这个*output_score是一个Nan值, 导致匹配数量一直是0.请问您在使用superglue推理的时候发现过这种情况吗? superpoint推理是没问题的.
        我的环境是Ubuntu20.04 CUDA12.1 + TensorRT 8.6.16

**Comment by xukuanHIT** [comment]
你好，目前转出来的superglue在TensorRT 8.6上运行可能会有问题。你可以尝试把版本降到8.5或者8.4，或者等我们下个版本的发布
